### ISSUE TITLE
Implementando o padrão de projeto adapter

### ISSUE THREAD

**Issue by Malivuca** [randersonLemos/mc426#30]
## Nessa issue o código de um dos componentes será refatorado para adotar o padrão de projeto do tipo comportamental `State`, cujas informações estão disponíveis em https://refactoring.guru/design-patterns/state

**Comment by randersonLemos** [comment]
Feito

**Comment by danilopereira10** [comment]
Tentei consertar o problema no adapter, para melhorar a nota:
https://github.com/randersonLemos/mc426/pull/52
