### ISSUE TITLE
Identificação e correção de code smells

### ISSUE THREAD

**Issue by randersonLemos** [randersonLemos/mc426#39]
Nessa issue, revisaremos o estado atual do código do projeto consultando o catálogo de Code Smells. Assim, identificaremos a incidencia de code smells no nosso codigo e iremos conserta-los

**Comment by randersonLemos** [comment]
### Code smell Bloater e Change Preventer
Tínhamos o Code Smell `Bloater` e `Change preventer`, que foram resolvidos na Issue #38. As mudanças podem ser visualizadas nos commits: 

* c2d51b829d380f983fcfc1e2674cb8538ea52d57
* 352bc8335acb3c3c5fb4883fcce70ccf7411eb1d

Aqui as implementações de métodos de autenticação, validação de usuários e acesso às demais informações do banco de dados foram encapsuladas pelas classes `Adapter` e `BackendFirebase`, de modo que os componentes do react, principalmente o formulário de cadastro de recebimento de alerta, foram os mais impactados pelas mudanças, tendo significativa redução de tamanho e melhor separação de conceitos (Code Smell `Bloater`). Também, com a implementação do Adpater para o backend, resolveu-se o Code Smell `Change preventer` pois todas as dependência e lógicas do backend estão concentradas nas mencionadas classes em vez de estarem espalhadas pelos componentes.
### Code smell Dispensable
Tínhamos o Code Smell `Dispensable`, que foi resolvido nesta Issue. As mudanças podem ser visualizadas no commit: 
* 87ceb1a62712d4a8248bc98ff0d5e7481a34ab2c

**Comment by Malivuca** [comment]
Essa issue foi resolvida nessa branch: https://github.com/randersonLemos/mc426/tree/39-Identifica%C3%A7%C3%A3o-e-corre%C3%A7%C3%A3o-de-code-smells

**Comment by danilopereira10** [comment]
Corrigidos também code Smells Couplers-Middle Man no BackendAdapter e Change Preventer - Shotgun Surgery no trecho SignUpProps que estava começando a ser usado em diversos arquivos diferentes

**Comment by danilopereira10** [comment]
Opa, as alterações na verdade foram aqui: https://github.com/randersonLemos/mc426/pull/52/files

O MiddleMan que foi criado na avaliação 4.1 foi corrigido aqui, ao se remover as dependências do código do firebase nas classes cliente. Essa parte seria classificada como o Code Smell Couplers Middle Man. Tudo foi feito nesse commit:
https://github.com/randersonLemos/mc426/pull/52/commits/32ffe89a9cb548bb661b1603a08cc8e6b134282c

O outro Code Smell que eu classifiquei como "Change Preventers - Shotgun Surgery" - https://github.com/randersonLemos/mc426/pull/52/commits/cb6e64c5389587f7e1ae221d643bda4f60206ae0 , eu resolvi nesse commit.

Na avaliação 4.1 eu só aproveitei para pontuar que eu tentei resolver o problema do BackendAdapter nesse mesmo commit https://github.com/randersonLemos/mc426/pull/52/commits/32ffe89a9cb548bb661b1603a08cc8e6b134282c
