### ISSUE TITLE
Envio seletivo de alertas

### ISSUE THREAD

**Issue by Neomixer** [randersonLemos/mc426#9]
Um destinatário pode desejar receber alguns tipos de alertas e não outros, sendo então imprescindível que este possa escolher que alertas receber.

Proponho que destinatários possam selecionar durante o cadastro as categorias de alerta que o interessam e que remetentes tenham que categorizar suas mensagens, que serão repassadas aos destinatários interessados.

Requere #6 e #4.

**Comment by randersonLemos** [comment]
Eu como remetente gostaria de enviar mensagens para pessoas que se enquadram em um determinado grupo, como idade ou local

**Comment by Malivuca** [comment]
Feito com #33
